# Generated by Django 6.0.3 on 2026-03-15 09:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='CashPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Kanika Acc, Cash lent Reshu', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommodityHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=10)),
                ('description', models.CharField(help_text='e.g. 20gm Coin - 1 (24k)', max_length=200)),
                ('purity', models.CharField(blank=True, help_text='e.g. 24k, 999', max_length=20)),
                ('weight_grams', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['commodity_type', '-weight_grams'],
            },
        ),
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_type', models.CharField(choices=[('GOLD', 'Gold'), ('SILVER', 'Silver')], max_length=10, unique=True)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['commodity_type'],
            },
        ),
        migrations.CreateModel(
            name='CryptoHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Crypto', max_length=100)),
                ('amount_invested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EPFEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contribution', models.DecimalField(decimal_places=2, default=0, help_text='Money added in this update', max_digits=14)),
                ('interest_earned', models.DecimalField(decimal_places=2, default=0, help_text='Interest credited in this update', max_digits=14)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, help_text='Running total after this update', max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'EPF Entry',
                'verbose_name_plural': 'EPF Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FixedDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('account_name', models.CharField(help_text='e.g. Atul Acc, HUF Acc, Blue Green Web', max_length=100)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in %', max_digits=5)),
                ('compounding', models.CharField(choices=[('SIMPLE', 'Simple Interest'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='QUARTERLY', max_length=10)),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'maturity_date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month this snapshot represents', unique=True)),
                ('data', models.JSONField(default=dict, help_text='Per-category breakdown: {category: {invested, current, returns}}')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_returns', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('money_added_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('returns_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='NPSEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contribution', models.DecimalField(decimal_places=2, default=0, help_text='Money added in this update', max_digits=14)),
                ('interest_earned', models.DecimalField(decimal_places=2, default=0, help_text='Returns credited in this update', max_digits=14)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, help_text='Running total after this update', max_digits=14)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NPS Entry',
                'verbose_name_plural': 'NPS Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZerodhaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('sheet_id', models.CharField(blank=True, help_text='Google Sheets spreadsheet ID', max_length=200)),
                ('sheet_range_stocks', models.CharField(blank=True, default='', help_text='Sheet name / range for stock holdings', max_length=100)),
                ('sheet_range_index_mf', models.CharField(blank=True, default='', help_text='Sheet name / range for index mutual funds', max_length=100)),
                ('sheet_range_other_mf', models.CharField(blank=True, default='', help_text='Sheet name / range for other mutual funds', max_length=100)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MutualFundHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=300)),
                ('fund_type', models.CharField(choices=[('INDEX', 'Index Fund'), ('OTHER', 'Other Mutual Fund')], max_length=10)),
                ('units', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mf_holdings', to='portfolio.zerodhaaccount')),
            ],
            options={
                'ordering': ['fund_name'],
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to='portfolio.zerodhaaccount')),
            ],
            options={
                'ordering': ['symbol'],
                'unique_together': {('account', 'symbol')},
            },
        ),
    ]
