# Generated by Django 6.0.3 on 2026-03-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. 50L, 1Cr', max_length=50)),
                ('target_amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'target_amount'],
            },
        ),
        migrations.RemoveField(
            model_name='epfentry',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='epfentry',
            name='interest_earned',
        ),
        migrations.RemoveField(
            model_name='epfentry',
            name='total_balance',
        ),
        migrations.AddField(
            model_name='epfentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='epfentry',
            name='entry_type',
            field=models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('INTEREST', 'Interest')], default='CONTRIBUTION', max_length=15),
        ),
    ]
