# Generated by Django 6.0.3 on 2026-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_financial_goal_refactor_epf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodityholding',
            name='purity',
            field=models.CharField(blank=True, choices=[('24k', '24k (999)'), ('22k', '22k (916)'), ('18k', '18k (750)'), ('14k', '14k (585)'), ('999', '999 (Fine Silver)'), ('925', '925 (Sterling)'), ('900', '900'), ('800', '800')], default='24k', max_length=20),
        ),
    ]
