# Generated by Django 6.0.3 on 2026-03-16 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_commodity_purity_choices'),
        ('tracker', '0008_monthlygoaladjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondholding',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bond_holdings', to='tracker.accountgroup'),
        ),
        migrations.AddField(
            model_name='cashposition',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_positions', to='tracker.accountgroup'),
        ),
        migrations.AddField(
            model_name='commodityholding',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commodity_holdings', to='tracker.accountgroup'),
        ),
        migrations.AddField(
            model_name='cryptoholding',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_holdings', to='tracker.accountgroup'),
        ),
        migrations.AddField(
            model_name='epfentry',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epf_entries', to='tracker.accountgroup'),
        ),
        migrations.AddField(
            model_name='financialgoal',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_goals', to='tracker.accountgroup'),
        ),
        migrations.AddField(
            model_name='fixeddeposit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_deposits', to='tracker.accountgroup'),
        ),
        migrations.AddField(
            model_name='monthlysnapshot',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to='tracker.accountgroup'),
        ),
        migrations.AddField(
            model_name='npsentry',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nps_entries', to='tracker.accountgroup'),
        ),
        migrations.AddField(
            model_name='zerodhaaccount',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zerodha_accounts', to='tracker.accountgroup'),
        ),
        migrations.AlterField(
            model_name='monthlysnapshot',
            name='month',
            field=models.DateField(help_text='First day of the month this snapshot represents'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysnapshot',
            unique_together={('group', 'month')},
        ),
    ]
