# Generated by Django 6.0.3 on 2026-03-16 17:40

from django.db import migrations


def assign_to_first_group(apps, schema_editor):
    """Assign all existing portfolio rows to the first AccountGroup (Atul Household)."""
    AccountGroup = apps.get_model('tracker', 'AccountGroup')
    first_group = AccountGroup.objects.order_by('id').first()
    if not first_group:
        return

    models_to_update = [
        apps.get_model('portfolio', 'ZerodhaAccount'),
        apps.get_model('portfolio', 'EPFEntry'),
        apps.get_model('portfolio', 'NPSEntry'),
        apps.get_model('portfolio', 'FixedDeposit'),
        apps.get_model('portfolio', 'CashPosition'),
        apps.get_model('portfolio', 'BondHolding'),
        apps.get_model('portfolio', 'CryptoHolding'),
        apps.get_model('portfolio', 'CommodityHolding'),
        apps.get_model('portfolio', 'FinancialGoal'),
        apps.get_model('portfolio', 'MonthlySnapshot'),
    ]
    for Model in models_to_update:
        Model.objects.filter(group__isnull=True).update(group=first_group)


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_add_group_to_portfolio_models'),
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(assign_to_first_group, migrations.RunPython.noop),
    ]
