# Generated by Django 6.0.3 on 2026-03-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_assign_existing_data_to_atul_group'),
        ('tracker', '0009_hraexpense_tracker_hra_user_id_a6beea_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='epfentry',
            index=models.Index(fields=['group', '-date'], name='portfolio_e_group_i_b008b7_idx'),
        ),
        migrations.AddIndex(
            model_name='fixeddeposit',
            index=models.Index(fields=['group', 'is_active'], name='portfolio_f_group_i_eeb227_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlysnapshot',
            index=models.Index(fields=['group', 'month'], name='portfolio_m_group_i_d001c8_idx'),
        ),
        migrations.AddIndex(
            model_name='mutualfundholding',
            index=models.Index(fields=['account', 'fund_type'], name='portfolio_m_account_92b6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='npsentry',
            index=models.Index(fields=['group', '-date'], name='portfolio_n_group_i_c9cfae_idx'),
        ),
    ]
