# Generated by Django 6.0.3 on 2026-03-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_epfentry_portfolio_e_group_i_b008b7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodityholding',
            name='purchase_price_per_gram',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price per gram at the time of purchase (INR)', max_digits=12),
        ),
    ]
