# Generated by Django 6.0.3 on 2026-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_backfill_commodity_purchase_price'),
        ('tracker', '0010_alter_monthlygoaladjustment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlysnapshot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='stockholding',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='monthlysnapshot',
            constraint=models.UniqueConstraint(fields=('group', 'month'), name='unique_group_month_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='stockholding',
            constraint=models.UniqueConstraint(fields=('account', 'symbol'), name='unique_account_symbol'),
        ),
    ]
