# Generated by Django 6.0.3 on 2026-03-19 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_monthlysnapshot_unique_together_and_more'),
        ('tracker', '0010_alter_monthlygoaladjustment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(max_length=50)),
                ('prompt_data', models.JSONField()),
                ('insights', models.JSONField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_insights', to='tracker.accountgroup')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
