# Generated by Django 6.0.3 on 2026-04-03 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_add_portfolio_insight'),
        ('tracker', '0013_rehash_existing_passwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='USStockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='UBER', max_length=20)),
                ('company_name', models.CharField(default='Uber Technologies', max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('vest_date', models.DateField(help_text='Date RSUs were vested / added')),
                ('purchase_price_usd', models.DecimalField(decimal_places=2, default=0, help_text='Stock price per share in USD at vest date', max_digits=12)),
                ('current_price_usd', models.DecimalField(decimal_places=2, default=0, help_text='Latest stock price per share in USD', max_digits=12)),
                ('purchase_usd_inr', models.DecimalField(decimal_places=2, default=0, help_text='USD/INR exchange rate at vest date', max_digits=10)),
                ('current_usd_inr', models.DecimalField(decimal_places=2, default=0, help_text='Latest USD/INR exchange rate', max_digits=10)),
                ('last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='us_stock_holdings', to='tracker.accountgroup')),
            ],
            options={
                'ordering': ['-vest_date'],
            },
        ),
    ]
