# Generated by Django 6.0.3 on 2026-03-11 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_month', models.DateField(help_text='The first month this new monthly goal applies to (format: YYYY-MM-01).')),
                ('new_monthly_goal', models.DecimalField(decimal_places=2, help_text='New monthly savings target from this month onwards.', max_digits=12)),
                ('reason', models.CharField(blank=True, help_text="Optional: reason for this change (e.g. 'salary hike')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_increments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['effective_month'],
            },
        ),
    ]
