# Generated by Django 6.0.3 on 2026-03-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_goalincrement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalincrement',
            name='new_monthly_goal',
        ),
        migrations.AddField(
            model_name='goalincrement',
            name='increment_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to add (or subtract) to the base monthly goal from this month onwards.', max_digits=12),
        ),
    ]
