# Generated by Django 6.0.3 on 2026-03-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_goalincrement_new_monthly_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hraexpense',
            name='hra_type',
            field=models.CharField(default='EXPENSE', max_length=20),
        ),
    ]
