# Generated by Django 6.0.3 on 2026-03-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_hraexpense_hra_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('TRANSFER', 'Transfer'), ('EXTRA_INCOME', 'Extra Income')], max_length=20),
        ),
    ]
