# Generated by Django 6.0.3 on 2026-03-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hraexpense',
            name='hra_type',
            field=models.CharField(choices=[('RENT_PAID', 'Rent Paid'), ('EXPENSE', 'Expense'), ('REVERT', 'Revert')], default='EXPENSE', max_length=20),
        ),
    ]
