# Generated by Django 6.0.3 on 2026-03-13 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_accountgroup_alter_user_user_type_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoalAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Month this adjustment applies to (format: YYYY-MM-01).')),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, help_text="Amount to add (or subtract) to this month's goal only.", max_digits=12)),
                ('reason', models.CharField(blank=True, help_text="Optional: reason for this one-off change (e.g. 'bonus', 'vacation').", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('user', 'month')},
            },
        ),
    ]
