# Generated by Django 6.0.3 on 2026-03-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_monthlygoaladjustment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='hraexpense',
            index=models.Index(fields=['user', 'date'], name='tracker_hra_user_id_a6beea_idx'),
        ),
        migrations.AddIndex(
            model_name='hraexpense',
            index=models.Index(fields=['user', 'hra_type', 'date'], name='tracker_hra_user_id_323131_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='tracker_tra_user_id_d71426_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'type', 'date'], name='tracker_tra_user_id_a850a4_idx'),
        ),
    ]
