# Generated by Django 6.0.3 on 2026-03-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_hraexpense_tracker_hra_user_id_a6beea_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlygoaladjustment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='monthlygoaladjustment',
            constraint=models.UniqueConstraint(fields=('user', 'month'), name='unique_user_month_adjustment'),
        ),
    ]
