# Generated by Django 6.0.3 on 2026-03-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_alter_monthlygoaladjustment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountgroup',
            name='portfolio_password',
            field=models.CharField(blank=True, default='', help_text='Password to access portfolio for this group. Leave blank to disable.', max_length=128),
        ),
    ]
