# Generated by Django 6.0.3 on 2026-03-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_accountgroup_portfolio_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='portfolio_password',
            field=models.CharField(blank=True, default='', help_text='Hashed password to access portfolio for this group.', max_length=256),
        ),
    ]
