# Generated by Django 6.0.3 on 2026-03-31 11:50

from django.contrib.auth.hashers import identify_hasher, make_password
from django.db import migrations


def hash_plaintext_passwords(apps, schema_editor):
    AccountGroup = apps.get_model('tracker', 'AccountGroup')
    for group in AccountGroup.objects.exclude(portfolio_password=''):
        try:
            identify_hasher(group.portfolio_password)
        except ValueError:
            group.portfolio_password = make_password(group.portfolio_password)
            group.save(update_fields=['portfolio_password'])


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_hash_portfolio_password'),
    ]

    operations = [
        migrations.RunPython(hash_plaintext_passwords, migrations.RunPython.noop),
    ]
