# Generated by Django 6.0.5 on 2026-05-26 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_webauthn_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('section', models.CharField(blank=True, default='', help_text="Free-text section/tag, e.g. 'Savings', 'Tax', 'Goal'", max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional linked amount (₹)', max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='tracker_not_user_id_74896f_idx'), models.Index(fields=['user', 'section'], name='tracker_not_user_id_ff32cf_idx')],
            },
        ),
    ]
