# Generated by Django 6.0.5 on 2026-05-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='financial_year',
            field=models.IntegerField(blank=True, help_text='Start year of the financial year (e.g. 2025 for FY 2025-26)', null=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['user', 'financial_year'], name='tracker_not_user_id_20fddb_idx'),
        ),
    ]
