# Generated by Django 6.0.5 on 2026-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_note_financial_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='initial_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='pending_type',
            field=models.CharField(blank=True, choices=[('CREDIT', 'To Receive'), ('DEBIT', 'To Pay')], default='', max_length=10),
        ),
    ]
